owner: jjeaby # GitHub username
repo: mew # GitHub repository name
sites: # List of endpoints to track
  - name: mecab jjeaby
    url: https://mecab.jjeaby.ml
  - name: doku jjeaby
    url: https://www.jjeaby.ml
  - name : je Secret Site
    url: $SECRET_SITE
assignees: # Users to assign downtime issues (optional)
  - jjeaby
status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/logo.svg
  name: JJEABY's Status
  baseUrl: /mew
  introTitle: JJEABY's Site Status."
  introMessage: This is a JJEABY's Site status page which uses **real-time**
  navbar:
    - title: GitHub
      href: https://github.com/jjeaby
